spring.application.name=SecureTaskManagerFinal

spring.datasource.url=jdbc:postgresql://localhost:5432/secure_task_manager
spring.datasource.username=postgres
spring.datasource.password=sp@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


jwt.secret=WDne9ncZi4S5YvWKXVYH9nkzHFlvf4vU3vAR7gNkzPC
jwt.expiration=900000
